### ISSUE TITLE
[BUG] camel_data -i light/all not working

### ISSUE THREAD

**Issue by pverkind** [CAMeL-Lab/camel_tools#116]
**Describe the bug**
Trying to download the data using the command mentioned in the documentation does not work and displays the help instead.
On Windows 11, Python 3.11.1.

**To Reproduce**
```
python.exe -m pip install --upgrade pip
pip install --upgrade camel-tools
camel_data -i light
```

**Expected behavior**
Downloads the data

**Screenshots**

![image](https://user-images.githubusercontent.com/16897431/233052177-9eb7ded2-5c94-4e28-9814-a199dec5f6ff.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Python 3.11.1.
 - CAMeL Tools v1.2.0 (installed via pip)

**Additional context**
`camel_data light` does install the data; `camel_data all` or `camel_data full` does not.

**Comment by owo** [comment]
There are two issues here:
1) Python 3.11 is not supported since one of our dependencies, pytorch, doesn't support it at this time. We currently only support Python 3.7-3.10. Once they add support for it, we will include it in our supported Python versions.
2) Because of 1) you are installing an older version of camel-tools (current version is 1.5.2) which did not depend on pytorch. It also used [a different command](https://camel-tools.readthedocs.io/en/v1.2.0/getting_started.html#installation) for installing data. As you can see from the screenshot of the help message you attached, the `-i` argument did not exist at that time.

I would suggest installing Python 3.10 and reinstalling camel-tools to get the latest version, otherwise we can't help you if you encounter any issues.
