### ISSUE TITLE
Encoding error while reading database

### ISSUE THREAD

**Issue by alvelvis** [CAMeL-Lab/camel_tools#16]
Hi,
I am experiencing an encoding error while reading calima_star database in a Windows environment, and that is due to the fact that database.py relies on default encoding:

```python3
with open(fpath, 'r') as dbfile:
```

Then, if I try to `db = CalimaStarDB.builtin_db()`, it will raise an UnicodeError for the database is in UTF-8 (I guess), and Python default encoding in Windows is that of the computer language (mine, CP1252). Is there any way I could specify the encoding while reading the builtin_db?

If I replace that line at database.py to the one below, the error will be fixed, but that is not straightforward since I intend to making camel_tools pip installable through requirements.

```python3
with open(fpath, 'r', encoding="utf-8") as dbfile:
```

Thanks in advance

**Comment by owo** [comment]
Hi @alvelvis,

> Is there any way I could specify the encoding while reading the builtin_db?

Yes there should be but I'm not aware of how to do that (or if it's even possible) on Windows.
On Unix-like systems you could set the following environment variables:

```bash
export LC_CTYPE=UTF-8

# You can use pt_BR.UTF-8 (I think) for Brazilian Portuguese for the variables below.
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```


This is the correct solution, and I'll be doing this for all `open()` calls in CAMeL Tools:

```python
with open(fpath, 'r', encoding="utf-8") as dbfile:
```

I will try to make a temporary fix in the next few days but I'm currently on break and can't give you a precise timeline for this.
This means you'll have to install CAMeL Tools from source and not pip.

However, please note that there are a larger set of changes to CAMeL Tools and the new API for the analyzer and database will not be backwards compatible.

Just keep that in mind as it would require some changes in your usage of the API once the new version is released.

**Comment by owo** [comment]
Hi @alvelvis ,

I've been doing some research on possible quick fixes you can use.
I just have to ask, are you using Python 2.7? If so, we are not supporting any Python version below 3.6 moving forward.
From my understanding, Python 3.4+ uses UTF-8 by default and that seems to be the case on my Windows machine running Python 3.6.

However, if you are using Python 2.7, you can try [this workaround](https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python). If that doesn't work, then I'm sorry to say that there's nothing we can do. [Python 2.7 is no longer supported by the Python organization](https://www.python.org/doc/sunset-python-2/) and some new features we are implementing have dependencies that only support Python 3.6+.

If you are using Python 3.6+, please let me know, perhaps there's something else going on.
Either way, future updates of CAMeL Tools will be using `encoding='utf-8'` in all 'open()' calls to insure unambiguous access to files.

**Comment by owo** [comment]
Ok, so I did some even more digging and there are other issues that need to be dealt with on a "plain" Windows setup.
In fact, it seems to be impossible to have a "plain" Windows setup at the moment.

In the latest version of camel_tools on *master* we have one dependency (perhaps more) that can only be compiled in a Unix-like environment. On Windows, you can either use [Cygwin](https://www.cygwin.com/), [MinGW](http://mingw.org/) or [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) to do this.

If you are using Windows 10, I would highly recommend using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). You'll have to resort to the other two options otherwise. However, I can't guarantee that other dependencies can be compiled under the other options.

I'm currently using [Ubuntu](https://ubuntu.com/wsl) with WSL2 enabled (this explains why I haven't had any issues when using `open()`).

While our over-arching goal is to make CAMeL Tools accessible on as many platforms as possible, all of us working on CAMeL Tools use macOS and/or Linux on a day-to-day basis. And while I've been refactoring the code-base recently to be as system-agnostic as possible, we still have restrictions from dependencies to deal with. For example, ideally, I would like to support Python 3.4+ but, because of another dependency, we can only support Python 3.6+.

For now, I'm closing this issue but I will look into better Windows compatibility at a later time.

I'm sorry for any frustration this may have caused.

**Comment by alvelvis** [comment]
Hi @owo ,
Thank you very much for your answers on this.
I've tried in two different Windows machines using Python 3.6 and 3.8, in both the default encoding is CP1252 for Python reading/writing files. I use Ubuntu WSL for coding, and in this environment UTF-8 is the default, the only issue is when trying to  use CAMEL in plain Windows. And, just as I said and since I have already tested, ensuring that the "encoding=utf-8" while reading the database in `database.py` does the trick, and I see you have already commited it to the repo. Will it be available in the "pip" install in the future? How does it work?

Thank you, again!

**Comment by owo** [comment]
> Will it be available in the "pip" install in the future?

Yes and no.

Yes the `"encoding=utf-8"` will be present in a future version on pip. However, like I mentioned before, there will be breaking changes in the API you'll need to account for. No, it will not be installable on "plain" Windows for the foreseeable future because of the issues I mentioned in my last response.

However, I will consider with the team if we should have an option to install just the components that will work on a "plain" Windows setup. This means that users won't have access to the Dialect Identification system (perhaps other components as well). The analyzer alone should work on a plain Windows setup without issues.

It will be some time from now before a new pip version is released, so please keep an eye out (you can also fill out the form in the README to get an email when the next version is released).

**Comment by alvelvis** [comment]
Got it, thanks.

**Comment by owo** [comment]
Hi @alvelvis,

Just a quick update.

So camel-tools should be installable on plain Windows now through the master branch.
I've added installation instructions. However, dialectid will not be available.

Also, camel_tools.calima_star is now camel_tools.morphology (this was the breaking changes I mentioned).
The usage is almost the same other than things being renamed (CalimaStarDB -> MorphologyDB, CalimaStarAnalyzer -> Analyzer, etc). Just take a look at the docs to see what changed.

A pip release should be coming in the next couple of weeks or so once everything else is stabilized.

**Comment by alvelvis** [comment]
This is great news, @owo ! Thank you for the renamed functions, too.
