### ISSUE TITLE
Disambiguation performance time

### ISSUE THREAD

**Issue by alvelvis** [CAMeL-Lab/camel_tools#21]
Hi, CAMeL team,
I wonder if you have already tested the disambiguation module performance in terms of time spent.
Using an Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz, it takes me around 35 minutes to tagging 1,108,058 words.
Is there something I can do to shorten this time or is the disambiguation really a costly process? The pipeline I've been using is the following (older Camel version):

```python3
# 6.7 seconds initialization
db = CalimaStarDB.builtin_db()
analyzer = CalimaStarAnalyzer(db)
disambiguator = MLEDisambiguator(analyzer)

# 3.8 seconds for sentence segmentation using NLTK
sentences = nltk.sent_tokenize(text)

for sentence in sentences:
    words = simple_word_tokenize(sentence) # 1 second for all sentences summed up
    disamb_words = disambiguator.disambiguate(words) # 2033 seconds (34 minutes) for all sentences summed up
```

Best

**Comment by owo** [comment]
Hi @alvelvis ,

Unfortunately the MLE is a bit slow due to the multiple passes of sorting we do to insure consistent results across runs.

We can speed things up by adding a caching option to the disambiguator as well as a slight optimization in sorting.
I'll do that in the next couple of days.

In the meantime, one thing you can do is for each de-diacritized word that you encounter, store the disambig results in a dictionary mapped to that word. If the word already exists in your dictionary, then you can use those stored results immediately.
This will use quite a bit of memory depending on how many unique words your data has, but would reduce the computation time significantly.

The caching option I'll implement would allow you to limit the number of words and their results stored in memory, with the least frequently seen words being evicted from the cache.

Please note though that caching will have no benefit if all the de-diacrtized words in your text are unique.

**Comment by owo** [comment]
Hi @alvelvis ,

I've implemented caching as I described.

On my machine I was able to go from 25 mins without caching to 2 mins with caching for a text file of around 1.5 million words.

Please give it a try and let me know how it goes.

**Comment by alvelvis** [comment]
Hi @owo ,
Thanks for the news. I could not test it it yet for two reasons:

1) `MorphologyDB.builtin_db()` returns the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "///personal-path///src/camel-tools/camel_tools/morphology/database.py", line 94, in builtin_db
    return MorphologyDB(str(Path(db_info.path, 'morphology.db')), flags)
  File "///personal-path///src/camel-tools/camel_tools/morphology/database.py", line 144, in __init__
    self._parse_dbfile(fpath)
  File "///personal-path///src/camel-tools/camel_tools/morphology/database.py", line 183, in _parse_dbfile
    with open(fpath, 'r', encoding='utf-8') as dbfile:
FileNotFoundError: [Errno 2] No such file or directory: '///personal-path///.camel_tools/data/morphology_db/calima-msa-r13/morphology.db'
```

And in fact, the folder "~/.camel_tools/data" is empty.

2) If I skip `builtin_db()` and use an absolute path to a database (I copied the .db from the previous CAMeL installation), I get the following error:
```
Traceback (most recent call last):
  File "arasas.py", line 160, in <module>
    annotation = annotate(text, args.output_format, args.lexicon, xml_full_tags=args.xml_full_tags)
  File "arasas.py", line 64, in annotate
    disamb_words = disambiguator.disambiguate(words)
  File "///personal-path///src/camel-tools/camel_tools/disambig/mle.py", line 239, in disambiguate
    return [self._disambiguate_word(w) for w in sentence]
  File "///personal-path///src/camel-tools/camel_tools/disambig/mle.py", line 239, in <listcomp>
    return [self._disambiguate_word(w) for w in sentence]
  File "///personal-path///src/camel-tools/camel_tools/disambig/mle.py", line 202, in _disambiguate_word
    scored_analyses = self._scored_analyses(word_dd)
  File "///personal-path///.local/lib/python3.6/site-packages/cachetools/decorators.py", line 22, in wrapper
    v = func(*args, **kwargs)
  File "///personal-path///src/camel-tools/camel_tools/disambig/mle.py", line 166, in _scored_analyses
    if self._mle is not None and word_dd in self._mle:
AttributeError: 'MLEDisambiguator' object has no attribute '_mle'
```

I installed the latest camel_tools from the latest commit: `pip3 install -e git://github.com/CAMeL-Lab/camel_tools.git@bc03c8ce769742b5aa15ac7fb1ba55944976d02e#egg=camel_tools`

Tell me if you need any further information. Thanks.

**Comment by owo** [comment]
Hi @alvelvis ,

> And in fact, the folder "~/.camel_tools/data" is empty.

Have you installed the [zipped data](https://github.com/CAMeL-Lab/camel_tools#installing-data) as well?
If not, please do so in order to use `MorphologyDB.builtin_db()`. I agree, this probably has to be renamed since technically, the database is now part of the zipped data that needs to be installed. 

> If I skip builtin_db() and use an absolute path to a database (I copied the .db from the previous CAMeL installation), I get the following error

Yes this is a bug that was introduced in a recent commit, I'll fix it soon. But it shouldn't be a problem once you have the data files installed and use `builtin_db()`. This issue occurs only when `mle_path` is not specified in the constructor arguments.
As, a rule of thumb please reinstall the data files when updating camel-tools from master for now.
Once we have created the next release on pypi this should not need to be done as frequently and would be indicated in the README and release notes when it is necessary.

**Comment by owo** [comment]
I have fixed the issue in my previous comment and is now on master.

**Comment by alvelvis** [comment]
Indeed, both errors are now fixed.
Regarding the performance, the same dataset with the same pipeline I showed above had its time shortened from 35 minutes to 12 minutes, great! Another dataset with similar number of words did not have its time much changed, still around 30 minutes, that might be due to low lexical variation in the dataset.

Thank you for the outstanding support.

**Comment by owo** [comment]
I'm glad I was able to help :)

One last thing, now that you have the data installed. I would suggest initializing the `MLEDisambiguator` using the [`pretrained`](https://camel-tools.readthedocs.io/en/latest/api/disambig/mle.html#camel_tools.disambig.mle.MLEDisambiguator.pretrained) method.

This will create a `MLEDisambiguator` instance with one of the provided MLE files and a pre-configured 'Analyzer' instance. This would reduce lines of code (since you don't have to create a `MorphologyDB` or an `Analyzer` yourself) and will provide more accurate results (due to an MLE file being provided).
