### ISSUE TITLE
error on Installations

### ISSUE THREAD

**Issue by HananBatarfi** [CAMeL-Lab/camel_tools#36]
I try to install CAMel tools and I get this error. I am using windows 10 and python 3 
and use this comment for installation 
pip install camel-tools -f https://download.pytorch.org/whl/torch_stable.html

![image](https://user-images.githubusercontent.com/55310826/102535457-4e329f80-40b9-11eb-9165-3cfe01ff350c.png)

**Comment by owo** [comment]
Hi @HananBatarfi 

The error is caused because you don't have Microsoft C++ Build Tools installed as per the error log you attached:

![102535457-4e329f80-40b9-11eb-9165-3cfe01ff350c](https://user-images.githubusercontent.com/544629/102683492-f7c57e00-41ea-11eb-8d96-5f8dd49b0293.png)

Can you please follow the link provided in the error message to install Microsoft C++ Build Tools and let me know what happens?
I'll add it as a requirement in the README once we verify that installing it solves the issue.

**Comment by HananBatarfi** [comment]
> Hi @HananBatarfi
> 
> The error is caused because you don't have Microsoft C++ Build Tools installed as per the error log you attached:
> 
> ![102535457-4e329f80-40b9-11eb-9165-3cfe01ff350c](https://user-images.githubusercontent.com/544629/102683492-f7c57e00-41ea-11eb-8d96-5f8dd49b0293.png)
> 
> Can you please follow the link provided in the error message to install Microsoft C++ Build Tools and let me know what happens?
> I'll add it as a requirement in the README once we verify that installing it solves the issue.

Thank you for your response,
yes it installed successfully.
