### ISSUE TITLE
[BUG] Title of new issue...

### ISSUE THREAD

**Issue by awadomar34** [CAMeL-Lab/camel_tools#37]
I believe there is a bug with the ```DialectIdentifier.train()```. I have downloaded the large data set and added it to the path. However, whenever I try and use the ```train()``` method, this error comes up:
```
No such file or directory: '/home/usr/.camel_tools/data/dialectid/default/corpus_26_train.tsv'
```

The code I use to produce this error is:
```
from camel_tools.dialectid import DialectIdentifier

model = DialectIdentifier().train()
```
I use:
 - Ubuntu 20
 - Python 3.8
 - camel-tools 1.0.1

**Comment by owo** [comment]
Hi @awadomar34 

We intentionally don't provide the training data as part of the data packages due to licensing issues.
I have removed the `train()` function from the [documentation](https://camel-tools.readthedocs.io/en/latest/api/dialectid.html) because of this specifically.
At the moment the train function is just used internally by us to generate the pre-built models but we will be:

1. providing instructions on how to obtain the training data we use then re-exposing the `train()` docs
2. re-implementing the training function to allow users to provide their own training data (allowing for other dialects than the ones we provide)

I can't give you an exact timeline of when this will happen but, for the moment, please bear with us and stick to only the **publicly** documented functionality.
