### ISSUE TITLE
[ENHANCEMENT] morphological analyzer

### ISSUE THREAD

**Issue by ryabhmd** [CAMeL-Lab/camel_tools#39]
**What feature would you like to improve?**
analyzer.analyze()

**Is your enhancement request related to a problem? Please describe.**
I'm not sure if this is intentional, but I couldn't find an explanation in the documentation. 
If I insert a text in the analyzer that is an Arabic non-words, it return an empty list. 
E.g. analyzer.analyze('لالالالا') -> []
However, if the text is in any other alphabet (e.g. analyzer.analyze('дадада')) , it returns an analysis stating 'source' as 'foreign'. 

**Describe the solution you'd like**
I would rather it being consistent. If the word does not exist in the morph DB, it should either always return an empty list, or always return an analysis. If the word has Arabic chars, the analysis can include the info that the word does not exist in your DB. 

Thanks!

**Comment by slkh** [comment]
Hi @ryabhmd

The empty list returned by `analyzer.analyze()` categorically means there is _no analysis_, in other words, no answer can be generated.
That is because you can use different [`backoff`](https://camel-tools.readthedocs.io/en/latest/api/morphology/analyzer.html#camel_tools.morphology.analyzer.Analyzer) options to generate answers for words with _no analysis_ or generate extra answers for words that got analyses.

The answer for strings containing non-Arabic alphabets, digits, and punctuation is deterministically generated without reliance on the database.

We will add more clarification regarding this in our documentation. Thanks!

**Comment by owo** [comment]
Hi @ryabhmd,

Our database ONLY contains Arabic entries.

Things like punctuation, digits, and foreign words are detected using regex patterns.
Since these particular entries are easy to detect, an analysis can easily be generated.
Returning an empty list for these is not an option just because they're not in the database.

As @slkh  mentioned, analyses WILL be generated if the `backoff` option is set. Backoff analyses are indicated as such in their `source` feature.

If we decided to encode a no analysis situation using a special object or `None`, you still need to do a check to see if you have analyses or not. By returning an empty list you don't have to do this check if, for example, you just want to iterate through the analyses.

**Comment by ryabhmd** [comment]
Thank you both for the explanation!
