### ISSUE TITLE
[BUG] Error when extracting downloaded data using camel_data full

### ISSUE THREAD

**Issue by esulaiman** [CAMeL-Lab/camel_tools#61]
I am working using Colab pro. I tried to install camel tools using the following command:
!pip install camel-tools
!camel_data full

Sometimes the installation was completed successfully and sometimes I encountered the following error:
Error: An error occurred while extracting downloaded data.

Do you have any clue why such an error is generated?

Thanks in advance.

**Comment by owo** [comment]
Since the error occurs during extraction, it's probably because there isn't enough disk space on the Colab instance.
We download the zipped data to a temporary directory before extracting to their final destination so there's a period of time where we are utilizing around twice disk space.
We recommend installing the data on Google drive and we have instructions on how to do so in the [Guided Tour](https://colab.research.google.com/drive/1Y3qCbD6Gw1KEw-lixQx1rI6WlyWnrnDS?usp=sharing).

**Comment by esulaiman** [comment]
thank you for your reply. 
I tried to extract the data on Google drive but the same error appeared again when running:
!export | camel_data full

**Comment by owo** [comment]
So it seems a lot of people have been trying to access the data files that we reached our Google Drive quota.
Can you try again 24 hours? If that sstill doesn't work, we'll have to find some other storage solution for our data.

**Comment by esulaiman** [comment]
Yes, I think this is the problem. When I tried last night it was working.
Thank you for your help :)

**Comment by owo** [comment]
No problem :)
