### ISSUE TITLE
Question about sentiment analyzer output

### ISSUE THREAD

**Issue by mragheb** [CAMeL-Lab/camel_tools#64]
Hello,
I am trying to use the Camel sentiment analyzer on a set of tweets that I have compiled. They are preprocessed (i.e, "cleaned") and are in a csv file. I am using pandas and am creating a new column with the assigned sentiment. THe problem is that every time I run the script, I only get labels for some of the initial rows, but not the rest. For example, when the file had 6000+ clean tweets, and after like ten hours (and several trials),  the most I got as SA labels was for the first 153 tweets . I tried a csv file with much less data , e.g. 500 tweets, and only got the first 52 labelled (after about 37 minutes). I am not sure what the issue is. Please advise, and thanks in advance.

**Comment by owo** [comment]
Hi @mragheb ,

Without any information on how you're using the sentiment analyzer, what system you're running on, etc, I can't even begin to think of what the issue is.

However, I wrote a little script to test the sentiment analyzer on a data set of a similar size to what you have described.

```python
from camel_tools.tokenizers.word import simple_word_tokenize
from camel_tools.sentiment import SentimentAnalyzer

# A sentence taken from wikipedia. It has the length of a longish tweet so we
# can test the average/worst-case runtime scenario.
sentence = 'إحصائيات رابطة ميلان المحدودة لكرة القدم، المعروفة أكثر باسم إيه سي ميلان، أو مجرد الميلان، هو نادي كرة قدم إيطالي، تأسس بتاريخ 16 ديسمبر 1899 على يد الإنجليزي هيربرت كيلبن.'

# This just separates punctuation from words. Not necessary but helps ith accuracy.
sentence = ' '.join(simple_word_tokenize(sentence))

# Create a list with 6000 copies of sentence
sentences = [ sentence ] * 6000

# Analyze sentiments
sa = SentimentAnalyzer.pretrained()
sentiments = sa.predict(sentences)

# Print the length of the generated sentiments.
# If all goes well, this should print out '6000'.
print(len(sentiments))
```

The above script run in under 11 minutes on my MacBook Pro (32GB RAM, 2.3 GHz Quad-Core Intel Core i7) using up 660 MB RAM and running on a single CPU core.
While the sentiment analyzer could be made faster by running on the GPU (not currently implemented for sentiment but is for NER), it shouldn't be as slow as what you've reported.

Can you please run the above script on your machine and let me know how it goes? Preferably using the `time` command if running on Linux or Mac to get an accurate run time.
