### ISSUE TITLE
CAMeL Tools : MLEDisambiguator error

### ISSUE THREAD

**Issue by FirasNacef** [CAMeL-Lab/camel_tools#85]
Hello everyone, I am having a problem using the disambiguator to lemmatize words in my arabic tweets.
As you can see in the first screenshot, I tried to apply a function that contains the code for the disambiguator. The second screenshot contains the error message I receive when running the code. The error occurs randomly when I feed the code a dataframe of 200 or less rows, and sometimes it works as it should. However, it keeps appearing consistently whenever I load more than 200 rows.
I tried some workarounds and tried loading other datasets, but I keep getting the same results.
You will find attached the notebook as well as the datasets I used to reproduce the error.

![Screen1](https://user-images.githubusercontent.com/101456672/163801925-95bc358c-2f41-4fd2-95d3-12b6312b2c35.png)
![screen2](https://user-images.githubusercontent.com/101456672/163801931-38aa1d16-81bf-4af4-a9e9-0cecd32ab86a.png)
[Disambiguator.zip](https://github.com/CAMeL-Lab/camel_tools/files/8505390/Disambiguator.zip)

**Comment by owo** [comment]
Hi @FirasNacef 

So there are multiple issues with the example you sent but there is one issue pertaining to camel-tools specifically.

In your TSV file, you have 132 sentences which contain an [Arabic superscript Alef](https://unicode-table.com/en/0670/) as an individual token after running `simple_word_tokenize()`, either because they are space separated and/or they immediately follow/precede a punctuation mark prior to calling `simple_word_tokenize()`.

This character is treated as a diacritic/tashkeel in camel_tools and would be removed prior to disambiguation. Because this character gets stripped, the disambiguator is now trying to disambiguate an empty string which leads to zero analyses being returned for that token.

You have two options for dealing with this:

1) Clean your sentences prior to calling `simple_word_tokenize()` perhaps by using [`dediac_ar()`](https://camel-tools.readthedocs.io/en/latest/api/utils/dediac.html#camel_tools.utils.dediac.dediac_ar).
2) Use a [DefaultTagger](https://camel-tools.readthedocs.io/en/stable/api/tagger/default.html#camel_tools.tagger.default.DefaultTagger) (instead of doing `[d.analyses[0].analysis['diac'] for d in disambig]`) which will provide sensible default values in the case when no analyses are returned.

**Comment by FirasNacef** [comment]
Hi @owo 

Thank you for your quick troubleshooting and response. 
Indeed that was the problem and I was able to resolve it by applying dediacritization prior to tokenization. 

Wish you and all CAMeL Lab team good luck.
